In [5]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
cross_3x3 = np.array([[0,1,0],[1,1,1],[0,1,0]],dtype=np.uint8)
print("Kernel or Structuring Element Cross 3x3")
print(cross_3x3)
img =  np.array([
		[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
		[0,0,1,1,0,0,1,1,1,1,0,0,0,0,0],
		[0,1,1,1,0,0,1,1,1,0,0,0,1,1,0],
		[0,1,1,1,1,1,1,1,1,0,0,0,1,1,0],
		[0,0,1,0,0,1,1,1,0,0,0,0,0,0,0],
		[0,0,0,0,0,0,1,0,0,0,1,1,0,0,0],
		[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
		[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	],dtype=np.uint16)
cross3x3 = cv.getStructuringElement(cv.MORPH_CROSS,(3,3))
show_erodecross3x3 = cv.erode(img,cross3x3,iterations=1)
print("Original Binary")
plt.imshow(img,cmap='gray'),plt.xticks([]),plt.yticks([])
plt.show()


Kernel or Structuring Element Cross 3x3
[[0 1 0]
 [1 1 1]
 [0 1 0]]
Original Binary
